DIE_AREA: [0, 0, 200, 250]

SYNTH_STRATEGY: "AREA 2"

FP_IO_VEXTEND: 0.0
FP_IO_HEXTEND: 0.0
FP_IO_HTHICKNESS_MULT: 2.0
FP_IO_VTHICKNESS_MULT: 2.0
FP_SIZING: "absolute"

IO_PIN_H_LENGTH: null
IO_PIN_V_LENGTH: null

RUN_HEURISTIC_DIODE_INSERTION: True
HEURISTIC_ANTENNA_THRESHOLD: 90

CTS_SINK_CLUSTERING_SIZE: 25
CTS_SINK_CLUSTERING_MAX_DIAMETER: 50
CTS_SINK_CLUSTERING_ENABLE: False

MAGIC_NO_EXT_UNIQUE: False

DESIGN_REPAIR_BUFFER_INPUT_PORTS: False
DESIGN_REPAIR_BUFFER_OUTPUT_PORTS: True

PL_TIME_DRIVEN: False

CLOCK_PERIOD: 20.0
CLOCK_PORT: "UserCLK"

GRT_ANTENNA_ITERS: 10
GRT_ALLOW_CONGESTION: true
GRT_REPAIR_ANTENNAS: True

PDN_MULTILAYER: false

BOTTOM_MARGIN_MULT: 1
TOP_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

PDN_SKIPTRIM: True

pdk::sky130A:
  #Floor planning
  FP_IO_HLAYER: "met3"
  FP_IO_VLAYER: "met2"

  # Routing
  RT_MAX_LAYER: met4

  # PDN
  PDN_VWIDTH: 1.6
  PDN_VSPACING: 3.7
  PDN_VPITCH: 30
  PDN_VOFFSET: 5

  PDN_HWIDTH: 1.6
  PDN_HSPACING: 3.7
  PDN_HPITCH: 30
  PDN_HOFFSET: 5

pdk::ihp-sg13g2:
  #Floor planning
  FP_IO_HLAYER: "Metal3"
  FP_IO_VLAYER: "Metal2"

  # Routing
  RT_MAX_LAYER: TopMetal1

  DIODE_CELL: "sg13g2_antennanp/A"

  # PDN
  PDN_VWIDTH: 2.2
  PDN_VSPACING: 4.0
  PDN_VPITCH: 75.6
  PDN_VOFFSET: 13.6

  PDN_HWIDTH: 2.0
  PDN_HSPACING: 4.0
  PDN_HPITCH: 75.6
  PDN_HOFFSET: 13.57
