RUN_POST_GPL_DESIGN_REPAIR: False
RUN_POST_CTS_RESIZER_TIMING: False
DESIGN_REPAIR_BUFFER_INPUT_PORTS: False
PDN_ENABLE_RAILS: False
RUN_ANTENNA_REPAIR: False
RUN_FILL_INSERTION: False
RUN_TAP_ENDCAP_INSERTION: False
RUN_CTS: False
RUN_IRDROP_REPORT: False
ERROR_ON_SYNTH_CHECKS: False

VDD_PIN: "VPWR"
GND_PIN: "VGND"

GRT_ALLOW_CONGESTION: True
MAGIC_NO_EXT_UNIQUE: True

KLAYOUT_CONFLICT_RESOLUTION: "SkipNewCell"

FABULOUS_HALO_SPACING: [1, 1, 1, 1]
FABULOUS_TILE_SPACING: [0, 0]

pdk::sky130A:
  FP_PDN_VERTICAL_LAYER: "met4"
  FP_PDN_HORIZONTAL_LAYER: "met5"

  FP_PDN_VWIDTH: 1.6
  FP_PDN_VSPACING: 3.7
  FP_PDN_VPITCH: 30
  FP_PDN_VOFFSET: 5

  FP_PDN_HWIDTH: 1.6
  FP_PDN_HSPACING: 3.7
  FP_PDN_HPITCH: 30
  FP_PDN_HOFFSET: 5

  RT_CLOCK_MAX_LAYER: "met4"
  RT_MAX_LAYER: "met4"
  DRT_MAX_LAYER: "met4"

pdk::ihp-sg13g2:
  PDN_VERTICAL_LAYER: TopMetal1
  PDN_HORIZONTAL_LAYER: TopMetal2

  PDN_VWIDTH: 2.2
  PDN_VSPACING: 4.0
  PDN_VPITCH: 75.6
  PDN_VOFFSET: 13.6

  PDN_HWIDTH: 2.0
  PDN_HSPACING: 4.0
  PDN_HPITCH: 75.6
  PDN_HOFFSET: 13.57

  # Routing
  RT_CLOCK_MAX_LAYER: TopMetal1
  RT_MAX_LAYER: TopMetal1
  DRT_MAX_LAYER: TopMetal1
