"""Golden-file regression test for the structural timing model.

Synthesizes the LUT4AB tile of the template project with Yosys, runs OpenSTA,
and compares every pip delay the routing model would emit for that tile against
a checked-in golden file. This locks down the whole real-timing pipeline
(techmap-aware synthesis, SDF parsing, register pass-through edges, navigation,
Dijkstra delay extraction), so any regression in delay extraction shows up as a
golden diff.

The test needs `yosys` and `sta` on PATH (run inside the Nix dev shell) and an
installed ihp-sg13g2 PDK; it skips otherwise. Regenerate the golden after an
intended behavior change with:

    task test -- --runslow --update-goldens \
        tests/timing_model_test/test_structural_timing_regression.py
"""

import shutil
from pathlib import Path

import pytest
from ciel.common import get_ciel_home

from fabulous.fabric_definition.cell_spec import StdCellLibrary
from fabulous.fabulous_repl.fabulous_repl import FABulousREPL
from fabulous.fabulous_repl.helper import create_project, gather_project_verilog_files
from fabulous.fabulous_settings import get_context, init_context
from fabulous.routing_model.graph_algorithms import DelayType
from fabulous.routing_model.tile_timing_model import (
    FABulousTileTimingModel,
    TimingModelMode,
)
from tests.conftest import run_cmd

TILE = "LUT4AB"
PDK = "ihp-sg13g2"
LIBERTY_RELPATH = Path("libs.ref/sg13g2_stdcell/lib/sg13g2_stdcell_typ_1p20V_25C.lib")
GOLDEN_FILE = (
    Path(__file__).parent / "golden" / f"{TILE.lower()}_structural_pips_{PDK}.csv"
)


def _require_tools_and_pdk() -> Path:
    """Skip unless yosys, sta, and the ihp-sg13g2 PDK are available.

    Returns
    -------
    Path
        The PDK family root (the directory FAB_PDK_ROOT should point at).
    """
    missing = [tool for tool in ("yosys", "sta") if shutil.which(tool) is None]
    if missing:
        pytest.skip(f"{missing} not on PATH (run inside the Nix dev shell)")
    pdk_family_root = Path(get_ciel_home()) / PDK
    if not (pdk_family_root / PDK / LIBERTY_RELPATH).exists():
        pytest.skip(f"{PDK} PDK not installed under {pdk_family_root}")
    return pdk_family_root


def _tile_pip_delays(project_dir: Path) -> list[str]:
    """Compute every pip delay line for the tile, as the routing model would.

    Mirrors `RoutingModelGenerator.generate`: tile-internal pips come from the
    switch matrix, tile-external pips from the tile's wire list, and the delays
    from `FABulousTileTimingModel.pip_delay`.

    Parameters
    ----------
    project_dir : Path
        The generated FABulous project to characterize.

    Returns
    -------
    list[str]
        ``src,dst,delay`` lines, one per unique pip of the tile.
    """
    cli = FABulousREPL(
        "verilog", force=False, interactive=False, verbose=False, debug=True
    )
    run_cmd(cli, "load_fabric")
    run_cmd(cli, "gen_fabric")

    fabric = cli.fabulousAPI.fabric
    ctx = get_context()
    variables = {
        "PROJ_DIR": str(ctx.proj_dir),
        "PDK": ctx.pdk,
        "PDK_ROOT": str(ctx.pdk_root),
    }
    library = StdCellLibrary.load(ctx.proj_dir, ctx.pdk, variables)

    model = FABulousTileTimingModel(
        fabric=fabric,
        verilog_files=gather_project_verilog_files(project_dir),
        tile_name=TILE,
        mode=TimingModelMode.STRUCTURAL,
        consider_wire_delay=False,
        delay_type=DelayType.MAX_ALL,
        delay_scaling_factor=1.0,
        library=library,
    )

    tile = fabric.tileDic[TILE]
    lines: list[str] = []
    for source, sinks in tile.switch_matrix.connections.items():
        for sink in sinks:
            lines.append(f"{sink},{source},{model.pip_delay(sink, source)}")
    external_pips = dict.fromkeys(
        (wire.source, wire.destination) for wire in tile.wireList
    )
    for src, dst in external_pips:
        lines.append(f"{src},{dst},{model.pip_delay(src, dst)}")
    return lines


@pytest.mark.slow
def test_lut4ab_structural_pip_delays_match_golden(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    request: pytest.FixtureRequest,
) -> None:
    """Every LUT4AB pip delay must match the golden reference exactly."""
    pdk_family_root = _require_tools_and_pdk()

    project_dir = tmp_path / "timing_project"
    monkeypatch.setenv("FAB_PROJ_DIR", str(project_dir))
    monkeypatch.setenv("FAB_PDK", PDK)
    monkeypatch.setenv("FAB_PDK_ROOT", str(pdk_family_root))
    create_project(project_dir)
    init_context(project_dir)

    lines = _tile_pip_delays(project_dir)

    if request.config.getoption("--update-goldens"):
        GOLDEN_FILE.parent.mkdir(parents=True, exist_ok=True)
        header = (
            f"# Structural pip delays (ns) for tile {TILE} on {PDK}.\n"
            f"# Generated by {Path(__file__).name} --update-goldens.\n"
            "# src,dst,delay\n"
        )
        GOLDEN_FILE.write_text(header + "\n".join(lines) + "\n")
        return

    assert GOLDEN_FILE.exists(), (
        f"Golden file {GOLDEN_FILE} is missing; generate it with "
        "--runslow --update-goldens"
    )
    golden = [
        line
        for line in GOLDEN_FILE.read_text().splitlines()
        if line and not line.startswith("#")
    ]
    assert lines == golden
