"""Progress tracking for routing-demand evaluation."""

from __future__ import annotations

from loguru import logger


class RoutingDemandProcessTracker:
    """Log routing-demand evaluator progress.

    Parameters
    ----------
    enabled : bool
        Whether logging is enabled.
    chunk_size : int
        Number of optimizer iterations between progress updates.
    """

    def __init__(self, enabled: bool, chunk_size: int = 10) -> None:
        self.enabled = enabled
        self.chunk_size = max(1, chunk_size)

    def start(self, tile_name: str) -> None:
        """Log pass start.

        Parameters
        ----------
        tile_name : str
            Tile name.
        """
        if self.enabled:
            logger.info(f"[RoutingDemandEvaluator] Start {tile_name}")

    def loaded_matrix(self, path: object, pips: int) -> None:
        """Log matrix load.

        Parameters
        ----------
        path : object
            Matrix path.
        pips : int
            PIP count.
        """
        if self.enabled:
            logger.info(f"[RoutingDemandEvaluator] Loaded {path} with {pips} PIPs")

    def generated_demands(self, count: int) -> None:
        """Log demand generation.

        Parameters
        ----------
        count : int
            Demand count.
        """
        if self.enabled:
            logger.info(f"[RoutingDemandEvaluator] Generated {count} demands")

    def demand_profile_start(
        self,
        profile_name: str,
        class_count: int,
        hard_budget: int,
        random_budget: int,
    ) -> None:
        """Log demand-profile generation start.

        Parameters
        ----------
        profile_name : str
            Demand profile name.
        class_count : int
            Number of demand classes in the profile.
        hard_budget : int
            Deterministic demand budget.
        random_budget : int
            Random demand budget.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Generating profile {}: "
                "classes={}, hard_budget={}, random_budget={}",
                profile_name,
                class_count,
                hard_budget,
                random_budget,
            )

    def demand_class_start(
        self,
        demand_class: str,
        class_index: int,
        class_count: int,
        budget: int,
    ) -> None:
        """Log one demand-class generation start.

        Parameters
        ----------
        demand_class : str
            Demand class name.
        class_index : int
            One-based class index.
        class_count : int
            Total profile class count.
        budget : int
            Demand budget for this class call.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Demand class {}/{} start: {}, budget={}",
                class_index,
                class_count,
                demand_class,
                budget,
            )

    def demand_class_done(
        self,
        demand_class: str,
        generated: int,
        elapsed_seconds: float,
    ) -> None:
        """Log one demand-class generation completion.

        Parameters
        ----------
        demand_class : str
            Demand class name.
        generated : int
            Number of demands generated by the class.
        elapsed_seconds : float
            Wall-clock seconds spent in the class generator.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Demand class done: {}, generated={}, "
                "elapsed={:.2f}s",
                demand_class,
                generated,
                elapsed_seconds,
            )

    def demand_profile_done(self, profile_name: str, generated: int) -> None:
        """Log demand-profile generation completion.

        Parameters
        ----------
        profile_name : str
            Demand profile name.
        generated : int
            Final number of generated demands.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Profile {} generated {} demands",
                profile_name,
                generated,
            )

    def evaluation_start(self, label: str) -> None:
        """Log one demand-oracle evaluation start.

        Parameters
        ----------
        label : str
            Evaluation label.
        """
        if self.enabled:
            logger.info("[RoutingDemandEvaluator] Evaluating {}", label)

    def routing_start(self, demand_count: int, max_iterations: int) -> None:
        """Log router start.

        Parameters
        ----------
        demand_count : int
            Number of demands to route.
        max_iterations : int
            Maximum router iterations.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Router start: demands={}, max_iterations={}",
                demand_count,
                max_iterations,
            )

    def routing_iteration_start(
        self,
        iteration: int,
        max_iterations: int,
        demand_count: int,
    ) -> None:
        """Log router iteration start.

        Parameters
        ----------
        iteration : int
            Current router iteration.
        max_iterations : int
            Maximum router iterations.
        demand_count : int
            Number of demands routed in this iteration.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Router iteration {}/{} start: demands={}",
                iteration,
                max_iterations,
                demand_count,
            )

    def routing_iteration_done(
        self,
        iteration: int,
        max_iterations: int,
        failed_sinks: int,
        congested_resources: int,
        max_resource_usage: int,
        elapsed_seconds: float,
    ) -> None:
        """Log router iteration completion.

        Parameters
        ----------
        iteration : int
            Current router iteration.
        max_iterations : int
            Maximum router iterations.
        failed_sinks : int
            Failed sink count after the iteration.
        congested_resources : int
            Number of resources over capacity.
        max_resource_usage : int
            Maximum observed resource usage.
        elapsed_seconds : float
            Wall-clock seconds spent in the iteration.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Router iteration {}/{} done: "
                "failed_sinks={}, congested_resources={}, max_usage={}, "
                "elapsed={:.2f}s",
                iteration,
                max_iterations,
                failed_sinks,
                congested_resources,
                max_resource_usage,
                elapsed_seconds,
            )

    def routing_done(
        self,
        iterations_used: int,
        failed_sinks: int,
        congested_resources: int,
        max_resource_usage: int,
    ) -> None:
        """Log router completion.

        Parameters
        ----------
        iterations_used : int
            Router iterations used.
        failed_sinks : int
            Final failed sink count.
        congested_resources : int
            Final number of resources over capacity.
        max_resource_usage : int
            Final maximum resource usage.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Router done: iterations={}, "
                "failed_sinks={}, congested_resources={}, max_usage={}",
                iterations_used,
                failed_sinks,
                congested_resources,
                max_resource_usage,
            )

    def optimizer_start(
        self,
        optimizer: str,
        target_pips: int,
        max_iterations: int,
    ) -> None:
        """Log optimizer start.

        Parameters
        ----------
        optimizer : str
            Optimizer name.
        target_pips : int
            Target number of removed PIPs.
        max_iterations : int
            Maximum optimizer iterations.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Optimizer {} start: "
                "target_removed_pips={}, max_iterations={}",
                optimizer,
                target_pips,
                max_iterations,
            )

    def optimizer_iteration(
        self,
        iteration: int,
        max_iterations: int,
        current_pips: int,
        accepted_pips: int,
        accepted_batches: int,
        rejected_batches: int,
    ) -> None:
        """Log optimizer iteration progress in chunks.

        Parameters
        ----------
        iteration : int
            Current optimizer iteration.
        max_iterations : int
            Maximum optimizer iterations.
        current_pips : int
            Current accepted PIP count.
        accepted_pips : int
            Accepted removed PIPs.
        accepted_batches : int
            Accepted candidate batches.
        rejected_batches : int
            Rejected candidate batches.
        """
        if not self.enabled:
            return
        if iteration % self.chunk_size != 0 and iteration != max_iterations:
            return
        pct = 100.0 * iteration / max_iterations if max_iterations else 100.0
        logger.info(
            "[RoutingDemandEvaluator] Optimizer iterations: "
            "{}/{} ({:.1f}%), current_pips={}, removed_pips={}, "
            "accepted_batches={}, rejected_batches={}",
            iteration,
            max_iterations,
            pct,
            current_pips,
            accepted_pips,
            accepted_batches,
            rejected_batches,
        )

    def monte_carlo_learning_iteration(
        self,
        iteration: int,
        max_iterations: int,
        average_loss: float,
        max_loss: float,
        weight_change_rate: float,
        scored_pips: int,
        sampled_pips: int,
        unsampled_pips: int,
        epoch: int,
        epoch_progress: int,
        epoch_size: int,
    ) -> None:
        """Log Monte Carlo importance-learning progress.

        Parameters
        ----------
        iteration : int
            Current learning iteration.
        max_iterations : int
            Maximum learning iterations.
        average_loss : float
            Average sampled loss so far.
        max_loss : float
            Maximum sampled loss so far.
        weight_change_rate : float
            Relative importance-weight change.
        scored_pips : int
            Number of PIPs with importance scores.
        sampled_pips : int
            Removable PIPs seen in at least one learning sample.
        unsampled_pips : int
            Removable PIPs not seen in learning samples.
        epoch : int
            Current 1-based shuffled learning epoch.
        epoch_progress : int
            PIPs consumed in the current learning epoch.
        epoch_size : int
            PIPs in one full learning epoch.
        """
        if not self.enabled:
            return
        if iteration % self.chunk_size != 0 and iteration != max_iterations:
            return
        pct = 100.0 * iteration / max_iterations if max_iterations else 100.0
        logger.info(
            "[RoutingDemandEvaluator] Monte Carlo learning: "
            "{}/{} ({:.1f}%), avg_loss={:.6f}, max_loss={:.6f}, "
            "weight_change={:.6f}, scored_pips={}, sampled_pips={}, "
            "unsampled_pips={}, epoch={}, epoch_pips={}/{}",
            iteration,
            max_iterations,
            pct,
            average_loss,
            max_loss,
            weight_change_rate,
            scored_pips,
            sampled_pips,
            unsampled_pips,
            epoch,
            epoch_progress,
            epoch_size,
        )

    def monte_carlo_pruning_iteration(
        self,
        iteration: int,
        max_iterations: int,
        current_pips: int,
        accepted_pips: int,
        accepted_batches: int,
        rejected_batches: int,
    ) -> None:
        """Log Monte Carlo pruning progress.

        Parameters
        ----------
        iteration : int
            Current pruning iteration.
        max_iterations : int
            Maximum pruning iterations.
        current_pips : int
            Current accepted routing PIP count.
        accepted_pips : int
            Accepted removed PIPs.
        accepted_batches : int
            Accepted pruning batches.
        rejected_batches : int
            Rejected pruning batches.
        """
        if not self.enabled:
            return
        if iteration % self.chunk_size != 0 and iteration != max_iterations:
            return
        pct = 100.0 * iteration / max_iterations if max_iterations else 100.0
        logger.info(
            "[RoutingDemandEvaluator] Monte Carlo pruning: "
            "{}/{} ({:.1f}%), current_pips={}, removed_pips={}, "
            "accepted_batches={}, rejected_batches={}",
            iteration,
            max_iterations,
            pct,
            current_pips,
            accepted_pips,
            accepted_batches,
            rejected_batches,
        )

    def optimizer_finish(
        self,
        removed_pips: int,
        final_pips: int,
        stop_reason: str,
    ) -> None:
        """Log optimizer completion.

        Parameters
        ----------
        removed_pips : int
            Accepted removed PIPs.
        final_pips : int
            Final PIP count.
        stop_reason : str
            Reason optimization stopped.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Optimizer done: "
                "removed_pips={}, final_pips={}, stop_reason={}",
                removed_pips,
                final_pips,
                stop_reason,
            )

    def done(self, hard_failed: int, soft_failed: int) -> None:
        """Log pass completion.

        Parameters
        ----------
        hard_failed : int
            Failed hard demands.
        soft_failed : int
            Failed soft demands.
        """
        if self.enabled:
            logger.info(
                "[RoutingDemandEvaluator] Done "
                f"hard_failed={hard_failed}, soft_failed={soft_failed}"
            )
