"""Protocols for ODB objects used in FABulous."""

# ruff: noqa: D102

from typing import Any, Protocol


class OdbReaderLike(Protocol):
    """Protocol describing the reader object provided by the click wrapper."""

    dbunits: float
    tech: Any
    block: Any
    name: str


class odbBoxLike(Protocol):
    """Protocol describing the odb.dbBox object."""

    def xMin(self) -> int: ...
    def yMin(self) -> int: ...
    def xMax(self) -> int: ...
    def yMax(self) -> int: ...


class odbBPinLike(Protocol):
    """Protocol describing the odb.dbBPin object."""

    def getBBox(self) -> odbBoxLike: ...


class odbBTermLike(Protocol):
    """Protocol describing the odb.dbBTerm object."""

    def getName(self) -> str: ...
    def getBPins(self) -> list[Any]: ...
    def getIoType(self) -> str: ...
    def getSigType(self) -> str: ...


class odbMasterLike(Protocol):
    """Protocol describing the odb.dbMaster object."""

    def getName(self) -> str: ...


class odbInstLike(Protocol):
    """Protocol describing the odb.dbInst object."""

    def getName(self) -> str: ...
    def getMaster(self) -> odbMasterLike: ...
    def getBBox(self) -> odbBoxLike: ...
    def isPlaced(self) -> bool: ...
    def findITerm(self, name: str) -> "odbITermLike | None": ...


class odbMTermLike(Protocol):
    """Protocol describing the odb.dbMTerm object."""

    def getName(self) -> str: ...


class odbITermLike(Protocol):
    """Protocol describing the odb.dbITerm object."""

    def getInst(self) -> odbInstLike: ...
    def getMTerm(self) -> odbMTermLike: ...
    def getIoType(self) -> str: ...
    def getSigType(self) -> str: ...
    def getNet(self) -> "odbNetLike | None": ...
    def disconnect(self) -> None: ...
    def connect(self, net: "odbNetLike") -> None: ...


class odbNetLike(Protocol):
    """Protocol describing the odb.dbNet object."""

    def getName(self) -> str: ...
    def getSigType(self) -> str: ...
    def getITerms(self) -> list[odbITermLike]: ...
    def getBTerms(self) -> list[odbBTermLike]: ...


class odbBlockLike(Protocol):
    """Protocol describing the odb.dbBlock object."""

    def getDieArea(self) -> odbBoxLike: ...
    def getInsts(self) -> list[odbInstLike]: ...
    def getBTerms(self) -> list[odbBTermLike]: ...
    def getNets(self) -> list[odbNetLike]: ...
    def findInst(self, name: str) -> odbInstLike | None: ...
    def findNet(self, name: str) -> odbNetLike | None: ...


class odbPointLike(Protocol):
    """Protocol describing the odb.dbPoint object."""

    def x(self) -> int: ...
    def y(self) -> int: ...


class odbRectLike(Protocol):
    """Protocol describing the odb.dbRect object."""

    def xMin(self) -> int: ...
    def yMin(self) -> int: ...
    def xMax(self) -> int: ...
    def yMax(self) -> int: ...
    def dx(self) -> int: ...
    def dy(self) -> int: ...
    def xCenter(self) -> int: ...
    def yCenter(self) -> int: ...
    def ll(self) -> odbPointLike: ...
    def ul(self) -> odbPointLike: ...
    def ur(self) -> odbPointLike: ...
    def lr(self) -> odbPointLike: ...
    def center(self) -> odbPointLike: ...
