"""Data models for FABulous tile building.

The tile builder creates a FABulous tile package from BEL RTL files and a small routing-
policy description. The models in this file keep user options, generated artifacts, and
reporting statistics structured for the builder, PnR pass wrapper, and architecture
synthesizer helper.
"""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path  # noqa: TC003

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from fabulous.fabric_definition.define import Direction  # noqa: TC001


class FabulousCsvKeyword(StrEnum):
    """FABulous CSV and fabric-file keywords used by the tile builder."""

    BEL = "BEL"
    END_TILE = "EndTILE"
    FABRIC_TILE_ENTRY = "Tile"
    GENERATE = "GENERATE"
    INCLUDE = "INCLUDE"
    MATRIX = "MATRIX"
    NULL = "NULL"
    PARAMETERS_END = "ParametersEnd"
    TILE = "TILE"


class FabulousSpecialFeature(StrEnum):
    """FABulous BEL and tile annotation names used for special routing."""

    CARRY = "CARRY"
    ENABLE = "ENABLE"
    RESET = "RESET"
    SHARED_ENABLE = "SHARED_ENABLE"
    SHARED_RESET = "SHARED_RESET"


class TileBuilderGeneratedWire(StrEnum):
    """Default names generated by tile_builder for tile-local helper wires."""

    CARRY_IN = "Ci"
    CARRY_OUT = "Co"
    ENABLE_BEGIN = "J_SEN_BEG"
    ENABLE_END = "J_SEN_END"
    GND = "GND"
    RESET_BEGIN = "J_SRST_BEG"
    RESET_END = "J_SRST_END"
    VCC = "VCC"


class RoutingPipPattern(StrEnum):
    """Routing-resource PIP pattern used for tile-local switch matrices."""

    NONE = "none"
    SUBSET = "subset"
    WILTON = "wilton"
    UNIVERSAL = "universal"


class RoutingTrackGroup(BaseModel):
    """Describe compatible routing tracks discovered from FABulous base ports.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    group_id : str
        Stable identifier used in reports and diagnostics.
    direction : Direction
        FABulous routing direction.
    x_offset : int
        X offset from the parsed FABulous port row.
    y_offset : int
        Y offset from the parsed FABulous port row.
    wire_count : int
        Number of tracks in the group.
    destination_rows : list[str]
        Switch-matrix rows driven by selectable sources.
    selectable_sources : list[str]
        Switch-matrix columns that can be selected by destination rows.
    """

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    group_id: str
    direction: Direction
    x_offset: int
    y_offset: int
    wire_count: int
    destination_rows: list[str]
    selectable_sources: list[str]


class RoutingPatternContext(BaseModel):
    """Provide normalized resources to one routing PIP pattern generator.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    groups : list[RoutingTrackGroup]
        Compatible routing track groups discovered from base resources.
    fs : int
        Maximum number of generated selectable sources per destination row.
    generate_straight : bool
        Whether same-direction routing PIPs may be generated.
    generate_turns : bool
        Whether cross-direction routing PIPs may be generated.
    """

    model_config = ConfigDict(frozen=True)

    groups: list[RoutingTrackGroup]
    fs: int
    generate_straight: bool
    generate_turns: bool


class RoutingPatternResult(BaseModel):
    """Return PIPs generated by a routing pattern.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    pairs : list[tuple[str, str]]
        Generated ``(destination_row, selectable_source)`` PIP pairs.
    warnings : tuple[str, ...]
        Non-fatal diagnostics from the pattern generator.
    generated_pips : int
        Number of unique generated PIP pairs.
    compatible_groups : int
        Number of routing track groups considered by the pattern.
    """

    model_config = ConfigDict(frozen=True)

    pairs: list[tuple[str, str]] = Field(default_factory=list)
    warnings: tuple[str, ...] = ()
    generated_pips: int = 0
    compatible_groups: int = 0


class ConnectionHierarchyOptions(BaseModel):
    """Describe optional JUMP-based local connection hierarchy.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    enabled : bool
        Whether ordinary BEL inputs should be fed through generated JUMP stages.
    levels : list[int]
        Maximum mux fanin for each generated hierarchy level.
    generate_jump_ports : bool
        Whether tile-builder should emit generated JUMP rows into the tile CSV.
    jump_prefix : str
        Base prefix for generated JUMP wire names.
    replace_direct_input_pips : bool
        Whether hierarchy PIPs replace direct routing-source-to-BEL-input PIPs.
    """

    model_config = ConfigDict(frozen=True)

    enabled: bool = False
    levels: list[int] = Field(default_factory=lambda: [4])
    generate_jump_ports: bool = True
    jump_prefix: str = "J_LOCAL"
    replace_direct_input_pips: bool = True

    @field_validator("levels")
    @classmethod
    def _validate_levels(cls, value: list[int]) -> list[int]:
        """Validate hierarchy level fanins.

        Parameters
        ----------
        value : list[int]
            User-provided hierarchy level fanins.

        Returns
        -------
        list[int]
            Validated hierarchy levels.

        Raises
        ------
        ValueError
            If any enabled hierarchy level is smaller than two.
        """
        if any(level < 2 for level in value):
            raise ValueError("connection hierarchy levels must be at least 2")
        return value

    @field_validator("jump_prefix")
    @classmethod
    def _validate_jump_prefix(cls, value: str) -> str:
        """Validate the generated JUMP prefix.

        Parameters
        ----------
        value : str
            User-provided JUMP prefix.

        Returns
        -------
        str
            Validated JUMP prefix.

        Raises
        ------
        ValueError
            If the prefix is empty.
        """
        if not value:
            raise ValueError("jump_prefix must not be empty")
        return value

    @model_validator(mode="after")
    def _validate_enabled_levels(self) -> ConnectionHierarchyOptions:
        """Validate cross-field hierarchy settings.

        Returns
        -------
        ConnectionHierarchyOptions
            Validated hierarchy options.

        Raises
        ------
        ValueError
            If hierarchy is enabled without at least one level.
        """
        if self.enabled and not self.levels:
            raise ValueError("enabled connection hierarchy requires at least one level")
        return self


class TileBel(BaseModel):
    """Describe one BEL RTL file and the instance prefixes used in a tile.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    verilog_path : Path
        Verilog or SystemVerilog source file containing the BEL module.
    prefixes : list[str]
        Instance prefixes used when adding this BEL to the generated tile.
    add_as_custom_prim : bool
        Whether the parsed BEL should be added to ``user_design/custom_prims.v``.
    """

    model_config = ConfigDict(frozen=True)

    verilog_path: Path
    prefixes: list[str] = Field(default_factory=lambda: [""])
    add_as_custom_prim: bool = True

    @field_validator("prefixes")
    @classmethod
    def _validate_prefixes(cls, value: list[str]) -> list[str]:
        """Validate that at least one prefix is provided.

        Parameters
        ----------
        value : list[str]
            User-provided prefix list.

        Returns
        -------
        list[str]
            Validated prefix list.

        Raises
        ------
        ValueError
            If the tuple is empty.
        """
        if not value:
            raise ValueError("prefixes must contain at least one entry")
        return value


class BaselineRouting(BaseModel):
    """Describe the initial FABulous switch-matrix list generation policy.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    use_fabulous_auto : bool
        If ``True``, emit ``MATRIX,GENERATE`` and let FABulous create the list.
    input_fanin : int
        Preferred number of routing sources for each ordinary BEL input.
    output_fanin : int
        Preferred mux size for routing destinations driven by BEL outputs.
    min_input_fanin : int
        Lowest BEL-input fanin allowed when fitting the config-bit budget.
    min_output_fanin : int
        Lowest BEL-output routing fanin allowed when fitting the config-bit budget.
    config_bit_margin : int
        Number of fabric config bits to leave unused.
    base_csv_includes : list[str]
        Tile CSV include paths for shared base wire descriptions.
    base_list_includes : list[str]
        Switch-matrix list include paths for shared base routing lists.
    derive_sources_from_base : bool
        Whether ordinary BEL inputs may use discovered base input ports.
    cover_unconnected_outputs : bool
        Whether to add coverage for base output rows not covered by included lists.
    emit_constants_if_missing : bool
        Whether to add local GND/VCC jump sources when the base does not define them.
    allow_bel_output_feedback_sources : bool
        Whether ordinary BEL input muxes may also select ordinary BEL outputs.
    routing_pip_pattern : RoutingPipPattern
        VPR-inspired routing-resource PIP pattern for tile-local routing tracks.
    routing_pip_fs : int
        Maximum number of generated routing sources per destination row.
    min_routing_pip_fs : int
        Lowest routing PIP pattern fanout allowed when fitting the config-bit budget.
    generate_straight_routing_pips : bool
        Whether same-direction route-through PIPs may be generated.
    generate_turn_routing_pips : bool
        Whether direction-changing route-through PIPs may be generated.
    connection_hierarchy : ConnectionHierarchyOptions
        Optional JUMP-based hierarchy for ordinary BEL input connections.
    """

    model_config = ConfigDict(frozen=True)

    use_fabulous_auto: bool = False
    input_fanin: int = 4
    output_fanin: int = 5
    min_input_fanin: int = 1
    min_output_fanin: int = 1
    config_bit_margin: int = 0
    base_csv_includes: list[str] = Field(
        default_factory=lambda: ["./../include/Base.csv"]
    )
    base_list_includes: list[str] = Field(
        default_factory=lambda: ["../include/Base.list"]
    )
    derive_sources_from_base: bool = True
    cover_unconnected_outputs: bool = True
    emit_constants_if_missing: bool = True
    allow_bel_output_feedback_sources: bool = True
    routing_pip_pattern: RoutingPipPattern = RoutingPipPattern.NONE
    routing_pip_fs: int = 3
    min_routing_pip_fs: int = 1
    generate_straight_routing_pips: bool = True
    generate_turn_routing_pips: bool = True
    connection_hierarchy: ConnectionHierarchyOptions = Field(
        default_factory=ConnectionHierarchyOptions
    )

    @field_validator(
        "input_fanin",
        "output_fanin",
        "min_input_fanin",
        "min_output_fanin",
        "routing_pip_fs",
        "min_routing_pip_fs",
    )
    @classmethod
    def _validate_positive(cls, value: int) -> int:
        """Validate that an integer field is positive.

        Parameters
        ----------
        value : int
            User-provided integer value.

        Returns
        -------
        int
            Validated integer value.

        Raises
        ------
        ValueError
            If the value is less than one.
        """
        if value < 1:
            raise ValueError("value must be at least 1")
        return value

    @field_validator("config_bit_margin")
    @classmethod
    def _validate_config_bit_margin(cls, value: int) -> int:
        """Validate that the config-bit margin is not negative.

        Parameters
        ----------
        value : int
            User-provided config-bit margin.

        Returns
        -------
        int
            Validated config-bit margin.

        Raises
        ------
        ValueError
            If the margin is negative.
        """
        if value < 0:
            raise ValueError("config_bit_margin must be non-negative")
        return value

    @field_validator("base_csv_includes", "base_list_includes")
    @classmethod
    def _validate_includes(cls, value: list[str]) -> list[str]:
        """Validate include path lists.

        Parameters
        ----------
        value : list[str]
            User-provided include paths.

        Returns
        -------
        list[str]
            Validated include paths.

        Raises
        ------
        ValueError
            If any include path is empty.
        """
        if any(not include for include in value):
            raise ValueError("include paths must not be empty")
        return value

    @field_validator("min_input_fanin")
    @classmethod
    def _validate_min_input_fanin(cls, value: int, info: object) -> int:
        """Validate the minimum input fanin against the preferred value.

        Parameters
        ----------
        value : int
            User-provided minimum fanin.
        info : object
            Pydantic validation context.

        Returns
        -------
        int
            Validated minimum fanin.

        Raises
        ------
        ValueError
            If the minimum fanin is greater than ``input_fanin``.
        """
        data = getattr(info, "data", {})
        input_fanin = data.get("input_fanin")
        if input_fanin is not None and value > input_fanin:
            raise ValueError("min_input_fanin must be <= input_fanin")
        return value

    @field_validator("min_output_fanin")
    @classmethod
    def _validate_min_output_fanin(cls, value: int, info: object) -> int:
        """Validate the minimum output fanin against the preferred value.

        Parameters
        ----------
        value : int
            User-provided minimum fanin.
        info : object
            Pydantic validation context.

        Returns
        -------
        int
            Validated minimum fanin.

        Raises
        ------
        ValueError
            If the minimum fanin is greater than ``output_fanin``.
        """
        data = getattr(info, "data", {})
        output_fanin = data.get("output_fanin")
        if output_fanin is not None and value > output_fanin:
            raise ValueError("min_output_fanin must be <= output_fanin")
        return value

    @field_validator("min_routing_pip_fs")
    @classmethod
    def _validate_min_routing_pip_fs(cls, value: int, info: object) -> int:
        """Validate the minimum routing pattern fanout.

        Parameters
        ----------
        value : int
            User-provided minimum routing pattern fanout.
        info : object
            Pydantic validation context.

        Returns
        -------
        int
            Validated minimum routing pattern fanout.

        Raises
        ------
        ValueError
            If the minimum fanout is greater than ``routing_pip_fs``.
        """
        data = getattr(info, "data", {})
        routing_pip_fs = data.get("routing_pip_fs")
        if routing_pip_fs is not None and value > routing_pip_fs:
            raise ValueError("min_routing_pip_fs must be <= routing_pip_fs")
        return value


class TileBuilderOptions(BaseModel):
    """Bundle all options for one tile-builder run.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    tile_name : str
        Name of the FABulous tile to generate.
    bels : list[TileBel]
        BEL source files and prefixes to instantiate.
    routing : BaselineRouting
        Baseline routing policy.
    tile_dir : Path | None
        Optional tile directory. ``None`` selects ``<project>/Tile/<tile_name>``.
    config_bit_capacity_override : int | None
        Optional total config-bit capacity. ``None`` uses the loaded FABulous fabric.
    register_in_fabric : bool
        Whether ``fabric.csv`` should receive a ``Tile`` entry for the new tile.
    track_progress : bool
        Whether progress should be logged.
    progress_chunk_size : int
        Number of BEL instances between progress messages.
    """

    model_config = ConfigDict(frozen=True)

    tile_name: str
    bels: list[TileBel]
    routing: BaselineRouting = Field(default_factory=BaselineRouting)
    tile_dir: Path | None = None
    config_bit_capacity_override: int | None = None
    register_in_fabric: bool = True
    track_progress: bool = True
    progress_chunk_size: int = 25

    @field_validator("tile_name")
    @classmethod
    def _validate_tile_name(cls, value: str) -> str:
        """Validate that a tile name is provided.

        Parameters
        ----------
        value : str
            User-provided tile name.

        Returns
        -------
        str
            Validated tile name.

        Raises
        ------
        ValueError
            If the tile name is empty.
        """
        if not value:
            raise ValueError("tile_name must not be empty")
        return value

    @field_validator("bels")
    @classmethod
    def _validate_bels(cls, value: list[TileBel]) -> list[TileBel]:
        """Validate that at least one BEL source is provided.

        Parameters
        ----------
        value : list[TileBel]
            User-provided BEL specifications.

        Returns
        -------
        list[TileBel]
            Validated BEL specifications.

        Raises
        ------
        ValueError
            If no BELs are provided.
        """
        if not value:
            raise ValueError("bels must contain at least one TileBel")
        return value

    @field_validator("progress_chunk_size")
    @classmethod
    def _validate_progress_chunk_size(cls, value: int) -> int:
        """Validate that progress chunks are positive.

        Parameters
        ----------
        value : int
            User-provided chunk size.

        Returns
        -------
        int
            Validated chunk size.

        Raises
        ------
        ValueError
            If the chunk size is less than one.
        """
        if value < 1:
            raise ValueError("progress_chunk_size must be at least 1")
        return value

    @field_validator("config_bit_capacity_override")
    @classmethod
    def _validate_config_bit_capacity_override(cls, value: int | None) -> int | None:
        """Validate optional config-bit capacity override.

        Parameters
        ----------
        value : int | None
            Optional config-bit capacity.

        Returns
        -------
        int | None
            Validated capacity.

        Raises
        ------
        ValueError
            If the override is not positive.
        """
        if value is not None and value <= 0:
            raise ValueError("config_bit_capacity_override must be positive")
        return value


class TileBuilderArtifact(BaseModel):
    """Describe one file generated or updated by the tile builder.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    kind : str
        Short artifact category.
    path : Path
        File path for the artifact.
    """

    model_config = ConfigDict(frozen=True)

    kind: str
    path: Path


class TileBuilderStats(BaseModel):
    """Summary statistics for a tile-builder run.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    bel_instances : int
        Number of generated BEL instances.
    unique_bel_modules : int
        Number of unique parsed BEL module names.
    bel_config_bits : int
        Total BEL configuration bits.
    matrix_config_bits : int
        Switch-matrix configuration bits.
    total_config_bits : int
        Total tile configuration bits.
    config_capacity : int
        Fabric configuration bit capacity for one tile.
    input_muxes : int
        Number of generated ordinary BEL-input muxes.
    output_muxes : int
        Number of generated BEL-output routing muxes.
    direct_connections : int
        Number of generated direct non-configurable connections.
    input_fanin_used : int
        Input fanin used by the baseline generator.
    output_fanin_used : int
        Output fanin used by the baseline generator.
    routing_pattern_pips : int
        Number of route-through PIPs generated by the routing pattern.
    routing_pattern_groups : int
        Number of routing track groups considered by the routing pattern.
    routing_pip_fs_used : int
        Routing pattern fanout used after budget reduction.
    connection_hierarchy_enabled : bool
        Whether JUMP-based connection hierarchy was used.
    connection_hierarchy_levels : tuple[int, ...]
        Configured hierarchy level fanins for the generated list.
    active_connection_hierarchy_levels : tuple[int, ...]
        Hierarchy level fanins that actually produced generated JUMP wires.
    generated_jump_wires : int
        Number of generated hierarchy JUMP wires.
    hierarchy_source_pips : int
        Number of PIPs from sources into hierarchy JUMP rows.
    hierarchy_sink_pips : int
        Number of PIPs from hierarchy outputs into BEL inputs.
    bypassed_hierarchy_inputs : int
        Number of hierarchy-enabled BEL inputs that were wired directly.
    """

    model_config = ConfigDict(frozen=True)

    bel_instances: int = 0
    unique_bel_modules: int = 0
    bel_config_bits: int = 0
    matrix_config_bits: int = 0
    total_config_bits: int = 0
    config_capacity: int = 0
    input_muxes: int = 0
    output_muxes: int = 0
    direct_connections: int = 0
    input_fanin_used: int = 0
    output_fanin_used: int = 0
    routing_pattern_pips: int = 0
    routing_pattern_groups: int = 0
    routing_pip_fs_used: int = 0
    connection_hierarchy_enabled: bool = False
    connection_hierarchy_levels: tuple[int, ...] = ()
    active_connection_hierarchy_levels: tuple[int, ...] = ()
    generated_jump_wires: int = 0
    hierarchy_source_pips: int = 0
    hierarchy_sink_pips: int = 0
    bypassed_hierarchy_inputs: int = 0


class BaselineListResult(BaseModel):
    """Result of generating one baseline switch-matrix list.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    text : str
        Complete list-file text.
    matrix_config_bits : int
        Estimated switch-matrix configuration bits including the base include.
    input_muxes : int
        Number of ordinary BEL-input muxes emitted by fabxplore.
    output_muxes : int
        Number of BEL-output routing muxes emitted by fabxplore.
    direct_connections : int
        Number of direct connections emitted by fabxplore.
    input_fanin_used : int
        Input fanin chosen after budget reduction.
    output_fanin_used : int
        Output fanin chosen after budget reduction.
    routing_pattern_pips : int
        Number of route-through PIPs generated by the routing pattern.
    routing_pattern_groups : int
        Number of routing track groups considered by the routing pattern.
    routing_pip_fs_used : int
        Routing pattern fanout chosen after budget reduction.
    generated_csv_lines : tuple[str, ...]
        Tile CSV rows generated by the baseline list, such as hierarchy JUMP wires.
    connection_hierarchy_enabled : bool
        Whether JUMP-based connection hierarchy was used.
    connection_hierarchy_levels : tuple[int, ...]
        Configured hierarchy level fanins for the generated list.
    active_connection_hierarchy_levels : tuple[int, ...]
        Hierarchy level fanins that actually produced generated JUMP wires.
    generated_jump_wires : int
        Number of generated hierarchy JUMP wires.
    hierarchy_source_pips : int
        Number of PIPs from sources into hierarchy JUMP rows.
    hierarchy_sink_pips : int
        Number of PIPs from hierarchy outputs into BEL inputs.
    bypassed_hierarchy_inputs : int
        Number of hierarchy-enabled BEL inputs that were wired directly.
    warnings : tuple[str, ...]
        Non-fatal warnings recorded during list generation.
    """

    model_config = ConfigDict(frozen=True)

    text: str
    matrix_config_bits: int
    input_muxes: int
    output_muxes: int
    direct_connections: int
    input_fanin_used: int
    output_fanin_used: int
    routing_pattern_pips: int = 0
    routing_pattern_groups: int = 0
    routing_pip_fs_used: int = 0
    generated_csv_lines: tuple[str, ...] = ()
    connection_hierarchy_enabled: bool = False
    connection_hierarchy_levels: tuple[int, ...] = ()
    active_connection_hierarchy_levels: tuple[int, ...] = ()
    generated_jump_wires: int = 0
    hierarchy_source_pips: int = 0
    hierarchy_sink_pips: int = 0
    bypassed_hierarchy_inputs: int = 0
    warnings: tuple[str, ...] = ()


class TileBuilderResult(BaseModel):
    """Result bundle produced by one tile-builder run.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    options : TileBuilderOptions
        Normalized options used for the run.
    tile_name : str
        Generated tile name.
    tile_dir : Path
        Generated tile directory.
    tile_csv : Path
        Tile CSV path.
    matrix_list : Path | None
        Generated baseline list path, or ``None`` when FABulous auto mode is used.
    parsed_bel_modules : tuple[str, ...]
        Parsed BEL module names, one entry per instance.
    artifacts : tuple[TileBuilderArtifact, ...]
        Generated or updated artifacts.
    stats : TileBuilderStats
        Summary statistics.
    warnings : tuple[str, ...]
        Non-fatal warnings.
    report_summary : str
        Human-readable report text.
    """

    model_config = ConfigDict(frozen=True)

    options: TileBuilderOptions
    tile_name: str
    tile_dir: Path
    tile_csv: Path
    matrix_list: Path | None = None
    parsed_bel_modules: tuple[str, ...] = ()
    artifacts: tuple[TileBuilderArtifact, ...] = ()
    stats: TileBuilderStats = Field(default_factory=TileBuilderStats)
    warnings: tuple[str, ...] = ()
    report_summary: str = ""
