"""Data models for FABulous tile building.

The tile builder creates a FABulous tile package from BEL RTL files and a small routing-
policy description. The models in this file keep user options, generated artifacts, and
reporting statistics structured for the builder, PnR pass wrapper, and architecture
synthesizer helper.
"""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path  # noqa: TC003

from pydantic import BaseModel, ConfigDict, Field, field_validator


class FabulousCsvKeyword(StrEnum):
    """FABulous CSV and fabric-file keywords used by the tile builder."""

    BEL = "BEL"
    END_TILE = "EndTILE"
    FABRIC_TILE_ENTRY = "Tile"
    GENERATE = "GENERATE"
    INCLUDE = "INCLUDE"
    MATRIX = "MATRIX"
    NULL = "NULL"
    PARAMETERS_END = "ParametersEnd"
    TILE = "TILE"


class FabulousSpecialFeature(StrEnum):
    """FABulous BEL and tile annotation names used for special routing."""

    CARRY = "CARRY"
    ENABLE = "ENABLE"
    RESET = "RESET"
    SHARED_ENABLE = "SHARED_ENABLE"
    SHARED_RESET = "SHARED_RESET"


class TileBuilderGeneratedWire(StrEnum):
    """Default names generated by tile_builder for tile-local helper wires."""

    CARRY_IN = "Ci"
    CARRY_OUT = "Co"
    ENABLE_BEGIN = "J_SEN_BEG"
    ENABLE_END = "J_SEN_END"
    GND = "GND"
    RESET_BEGIN = "J_SRST_BEG"
    RESET_END = "J_SRST_END"
    VCC = "VCC"


class TileBel(BaseModel):
    """Describe one BEL RTL file and the instance prefixes used in a tile.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    verilog_path : Path
        Verilog or SystemVerilog source file containing the BEL module.
    prefixes : list[str]
        Instance prefixes used when adding this BEL to the generated tile.
    add_as_custom_prim : bool
        Whether the parsed BEL should be added to ``user_design/custom_prims.v``.
    """

    model_config = ConfigDict(frozen=True)

    verilog_path: Path
    prefixes: list[str] = Field(default_factory=lambda: [""])
    add_as_custom_prim: bool = True

    @field_validator("prefixes")
    @classmethod
    def _validate_prefixes(cls, value: list[str]) -> list[str]:
        """Validate that at least one prefix is provided.

        Parameters
        ----------
        value : list[str]
            User-provided prefix list.

        Returns
        -------
        list[str]
            Validated prefix list.

        Raises
        ------
        ValueError
            If the tuple is empty.
        """
        if not value:
            raise ValueError("prefixes must contain at least one entry")
        return value


class BaselineRouting(BaseModel):
    """Describe the initial FABulous switch-matrix list generation policy.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    use_fabulous_auto : bool
        If ``True``, emit ``MATRIX,GENERATE`` and let FABulous create the list.
    input_fanin : int
        Preferred number of routing sources for each ordinary BEL input.
    output_fanin : int
        Preferred mux size for routing destinations driven by BEL outputs.
    min_input_fanin : int
        Lowest BEL-input fanin allowed when fitting the config-bit budget.
    min_output_fanin : int
        Lowest BEL-output routing fanin allowed when fitting the config-bit budget.
    config_bit_margin : int
        Number of fabric config bits to leave unused.
    base_csv_includes : list[str]
        Tile CSV include paths for shared base wire descriptions.
    base_list_includes : list[str]
        Switch-matrix list include paths for shared base routing lists.
    derive_sources_from_base : bool
        Whether ordinary BEL inputs may use discovered base input ports.
    cover_unconnected_outputs : bool
        Whether to add coverage for base output rows not covered by included lists.
    emit_constants_if_missing : bool
        Whether to add local GND/VCC jump sources when the base does not define them.
    allow_bel_output_feedback_sources : bool
        Whether ordinary BEL input muxes may also select ordinary BEL outputs.
    """

    model_config = ConfigDict(frozen=True)

    use_fabulous_auto: bool = False
    input_fanin: int = 4
    output_fanin: int = 5
    min_input_fanin: int = 1
    min_output_fanin: int = 1
    config_bit_margin: int = 0
    base_csv_includes: list[str] = Field(
        default_factory=lambda: ["./../include/Base.csv"]
    )
    base_list_includes: list[str] = Field(
        default_factory=lambda: ["../include/Base.list"]
    )
    derive_sources_from_base: bool = True
    cover_unconnected_outputs: bool = True
    emit_constants_if_missing: bool = True
    allow_bel_output_feedback_sources: bool = True

    @field_validator(
        "input_fanin",
        "output_fanin",
        "min_input_fanin",
        "min_output_fanin",
    )
    @classmethod
    def _validate_positive(cls, value: int) -> int:
        """Validate that an integer field is positive.

        Parameters
        ----------
        value : int
            User-provided integer value.

        Returns
        -------
        int
            Validated integer value.

        Raises
        ------
        ValueError
            If the value is less than one.
        """
        if value < 1:
            raise ValueError("value must be at least 1")
        return value

    @field_validator("config_bit_margin")
    @classmethod
    def _validate_config_bit_margin(cls, value: int) -> int:
        """Validate that the config-bit margin is not negative.

        Parameters
        ----------
        value : int
            User-provided config-bit margin.

        Returns
        -------
        int
            Validated config-bit margin.

        Raises
        ------
        ValueError
            If the margin is negative.
        """
        if value < 0:
            raise ValueError("config_bit_margin must be non-negative")
        return value

    @field_validator("base_csv_includes", "base_list_includes")
    @classmethod
    def _validate_includes(cls, value: list[str]) -> list[str]:
        """Validate include path lists.

        Parameters
        ----------
        value : list[str]
            User-provided include paths.

        Returns
        -------
        list[str]
            Validated include paths.

        Raises
        ------
        ValueError
            If any include path is empty.
        """
        if any(not include for include in value):
            raise ValueError("include paths must not be empty")
        return value

    @field_validator("min_input_fanin")
    @classmethod
    def _validate_min_input_fanin(cls, value: int, info: object) -> int:
        """Validate the minimum input fanin against the preferred value.

        Parameters
        ----------
        value : int
            User-provided minimum fanin.
        info : object
            Pydantic validation context.

        Returns
        -------
        int
            Validated minimum fanin.

        Raises
        ------
        ValueError
            If the minimum fanin is greater than ``input_fanin``.
        """
        data = getattr(info, "data", {})
        input_fanin = data.get("input_fanin")
        if input_fanin is not None and value > input_fanin:
            raise ValueError("min_input_fanin must be <= input_fanin")
        return value

    @field_validator("min_output_fanin")
    @classmethod
    def _validate_min_output_fanin(cls, value: int, info: object) -> int:
        """Validate the minimum output fanin against the preferred value.

        Parameters
        ----------
        value : int
            User-provided minimum fanin.
        info : object
            Pydantic validation context.

        Returns
        -------
        int
            Validated minimum fanin.

        Raises
        ------
        ValueError
            If the minimum fanin is greater than ``output_fanin``.
        """
        data = getattr(info, "data", {})
        output_fanin = data.get("output_fanin")
        if output_fanin is not None and value > output_fanin:
            raise ValueError("min_output_fanin must be <= output_fanin")
        return value


class TileBuilderOptions(BaseModel):
    """Bundle all options for one tile-builder run.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    tile_name : str
        Name of the FABulous tile to generate.
    bels : list[TileBel]
        BEL source files and prefixes to instantiate.
    routing : BaselineRouting
        Baseline routing policy.
    tile_dir : Path | None
        Optional tile directory. ``None`` selects ``<project>/Tile/<tile_name>``.
    config_bit_capacity_override : int | None
        Optional total config-bit capacity. ``None`` uses the loaded FABulous fabric.
    register_in_fabric : bool
        Whether ``fabric.csv`` should receive a ``Tile`` entry for the new tile.
    register_tile_in_fpga_model : bool
        Whether the active PnR bridge should reload the project and graph after
        a successful build.
    track_progress : bool
        Whether progress should be logged.
    progress_chunk_size : int
        Number of BEL instances between progress messages.
    """

    model_config = ConfigDict(frozen=True)

    tile_name: str
    bels: list[TileBel]
    routing: BaselineRouting = Field(default_factory=BaselineRouting)
    tile_dir: Path | None = None
    config_bit_capacity_override: int | None = None
    register_in_fabric: bool = True
    register_tile_in_fpga_model: bool = True
    track_progress: bool = True
    progress_chunk_size: int = 25

    @field_validator("tile_name")
    @classmethod
    def _validate_tile_name(cls, value: str) -> str:
        """Validate that a tile name is provided.

        Parameters
        ----------
        value : str
            User-provided tile name.

        Returns
        -------
        str
            Validated tile name.

        Raises
        ------
        ValueError
            If the tile name is empty.
        """
        if not value:
            raise ValueError("tile_name must not be empty")
        return value

    @field_validator("bels")
    @classmethod
    def _validate_bels(cls, value: list[TileBel]) -> list[TileBel]:
        """Validate that at least one BEL source is provided.

        Parameters
        ----------
        value : list[TileBel]
            User-provided BEL specifications.

        Returns
        -------
        list[TileBel]
            Validated BEL specifications.

        Raises
        ------
        ValueError
            If no BELs are provided.
        """
        if not value:
            raise ValueError("bels must contain at least one TileBel")
        return value

    @field_validator("progress_chunk_size")
    @classmethod
    def _validate_progress_chunk_size(cls, value: int) -> int:
        """Validate that progress chunks are positive.

        Parameters
        ----------
        value : int
            User-provided chunk size.

        Returns
        -------
        int
            Validated chunk size.

        Raises
        ------
        ValueError
            If the chunk size is less than one.
        """
        if value < 1:
            raise ValueError("progress_chunk_size must be at least 1")
        return value

    @field_validator("config_bit_capacity_override")
    @classmethod
    def _validate_config_bit_capacity_override(cls, value: int | None) -> int | None:
        """Validate optional config-bit capacity override.

        Parameters
        ----------
        value : int | None
            Optional config-bit capacity.

        Returns
        -------
        int | None
            Validated capacity.

        Raises
        ------
        ValueError
            If the override is not positive.
        """
        if value is not None and value <= 0:
            raise ValueError("config_bit_capacity_override must be positive")
        return value


class TileBuilderArtifact(BaseModel):
    """Describe one file generated or updated by the tile builder.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    kind : str
        Short artifact category.
    path : Path
        File path for the artifact.
    """

    model_config = ConfigDict(frozen=True)

    kind: str
    path: Path


class TileBuilderStats(BaseModel):
    """Summary statistics for a tile-builder run.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    bel_instances : int
        Number of generated BEL instances.
    unique_bel_modules : int
        Number of unique parsed BEL module names.
    bel_config_bits : int
        Total BEL configuration bits.
    matrix_config_bits : int
        Switch-matrix configuration bits.
    total_config_bits : int
        Total tile configuration bits.
    config_capacity : int
        Fabric configuration bit capacity for one tile.
    input_muxes : int
        Number of generated ordinary BEL-input muxes.
    output_muxes : int
        Number of generated BEL-output routing muxes.
    direct_connections : int
        Number of generated direct non-configurable connections.
    input_fanin_used : int
        Input fanin used by the baseline generator.
    output_fanin_used : int
        Output fanin used by the baseline generator.
    """

    model_config = ConfigDict(frozen=True)

    bel_instances: int = 0
    unique_bel_modules: int = 0
    bel_config_bits: int = 0
    matrix_config_bits: int = 0
    total_config_bits: int = 0
    config_capacity: int = 0
    input_muxes: int = 0
    output_muxes: int = 0
    direct_connections: int = 0
    input_fanin_used: int = 0
    output_fanin_used: int = 0


class BaselineListResult(BaseModel):
    """Result of generating one baseline switch-matrix list.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    text : str
        Complete list-file text.
    matrix_config_bits : int
        Estimated switch-matrix configuration bits including the base include.
    input_muxes : int
        Number of ordinary BEL-input muxes emitted by fabxplore.
    output_muxes : int
        Number of BEL-output routing muxes emitted by fabxplore.
    direct_connections : int
        Number of direct connections emitted by fabxplore.
    input_fanin_used : int
        Input fanin chosen after budget reduction.
    output_fanin_used : int
        Output fanin chosen after budget reduction.
    warnings : tuple[str, ...]
        Non-fatal warnings recorded during list generation.
    """

    model_config = ConfigDict(frozen=True)

    text: str
    matrix_config_bits: int
    input_muxes: int
    output_muxes: int
    direct_connections: int
    input_fanin_used: int
    output_fanin_used: int
    warnings: tuple[str, ...] = ()


class TileBuilderResult(BaseModel):
    """Result bundle produced by one tile-builder run.

    Attributes
    ----------
    model_config
        Pydantic model configuration.
    options : TileBuilderOptions
        Normalized options used for the run.
    tile_name : str
        Generated tile name.
    tile_dir : Path
        Generated tile directory.
    tile_csv : Path
        Tile CSV path.
    matrix_list : Path | None
        Generated baseline list path, or ``None`` when FABulous auto mode is used.
    parsed_bel_modules : tuple[str, ...]
        Parsed BEL module names, one entry per instance.
    artifacts : tuple[TileBuilderArtifact, ...]
        Generated or updated artifacts.
    stats : TileBuilderStats
        Summary statistics.
    warnings : tuple[str, ...]
        Non-fatal warnings.
    report_summary : str
        Human-readable report text.
    """

    model_config = ConfigDict(frozen=True)

    options: TileBuilderOptions
    tile_name: str
    tile_dir: Path
    tile_csv: Path
    matrix_list: Path | None = None
    parsed_bel_modules: tuple[str, ...] = ()
    artifacts: tuple[TileBuilderArtifact, ...] = ()
    stats: TileBuilderStats = Field(default_factory=TileBuilderStats)
    warnings: tuple[str, ...] = ()
    report_summary: str = ""
