name: Test fabric generation against base branch

on: [pull_request]

jobs:
  run_sim_makefile_on_base_project:
    name: Run fabric generator flow and simulation with FABulous makefile against base branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Verilog
            type: verilog 
          - name: VHDL
            type: vhdl

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.base_ref }} 
      - uses: ./.github/actions/prepare_FABulous_container
      - name: generate old project
        run: |
          FABulous -c /tmp/demo_${{ matrix.type }} -w ${{ matrix.type }}

      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare_FABulous_container
      - name: Run fabric generator flow and simulation with FABulous makefile
        id: run_simulation
        continue-on-error: true
        run: |
          cd /tmp/demo_${{ matrix.type }}/Test
          make FAB_sim
      
      - name: Manual approval for failed backward-compatibility check
        if: ${{ steps.run_simulation.outcome == 'failure' }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: FPGA-Research
          minimum-approvals: 2
          issue-title: "Backwards compatibility test failed for ${{ matrix.name }} - Manual approval required"
          issue-body: |
            The backwards compatibility test for ${{ matrix.name }} has failed.
            
            **PR:** ${{ github.event.pull_request.title }}
            **Branch:** ${{ github.head_ref }}
            **Matrix Type:** ${{ matrix.type }}
            
            Please review the failure and approve if the breaking change is acceptable.
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
      
      - name: Fail workflow if simulation failed and not approved
        if: ${{ steps.run_simulation.outcome == 'failure' }}
        run: exit 1
