name: Test fabric generation against base branch

on:
  pull_request:
    paths:
      - 'fabulous/**'
      - 'tests/**'
      - 'pyproject.toml'
      - '.github/workflows/backwards-compatibility.yml'
      - '.github/actions/**'

jobs:
  generate_old_project:
    name: Generate old project (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Verilog
            type: verilog
          - name: VHDL
            type: vhdl
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.base_ref }}
      - uses: ./.github/actions/prepare_FABulous_container
      - name: Generate project with base branch FABulous
        run: |
          uv run FABulous -c /tmp/demo_${{ matrix.type }} -w ${{ matrix.type }}
      - name: Upload generated project
        uses: actions/upload-artifact@v4
        with:
          name: demo-${{ matrix.type }}-base
          path: /tmp/demo_${{ matrix.type }}

  run_simulation:
    name: Run simulation with PR branch against base project (${{ matrix.name }})
    needs: generate_old_project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Verilog
            type: verilog
          - name: VHDL
            type: vhdl
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare_FABulous_container
      - name: Download base project
        uses: actions/download-artifact@v4
        with:
          name: demo-${{ matrix.type }}-base
          path: /tmp/demo_${{ matrix.type }}
      - name: Run fabric generator flow and simulation with FABulous makefile
        run: |
          cd /tmp/demo_${{ matrix.type }}/Test
          make FAB_sim
