name: Test fabric generation against base branch

on: [pull_request]

jobs:
  run_sim_makefile_on_base_project:
    name: Run fabric generator flow and simulation with FABulous makefile against base branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Verilog
            type: verilog 
          - name: VHDL
            type: vhdl

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.base_ref }} 
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: generate old project
        run: |
          nix develop --command uv run FABulous -c /tmp/demo_${{ matrix.type }} -w ${{ matrix.type }}

      - uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run fabric generator flow and simulation with FABulous makefile
        id: run_simulation
        continue-on-error: true
        run: |
          nix develop --command bash -c 'cd /tmp/demo_${{ matrix.type }}/Test && make FAB_sim'
