name: "Docs Build Check"

on:
  push:
    branches: [ master, FABulous2.0-development ]
  pull_request:
    branches: [ master, FABulous2.0-development ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ammaraskar/sphinx-action@8.2.3
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: "0.0"
        with:
          pre-build-command: "pip install uv && uv sync --directory ."
          build-command: 'make html SPHINXOPTS+="-W --keep-going"'
          docs-folder: "docs/"
