name: Test FABulous

on: [push, pull_request]

jobs:
  run_verilog_simulation_CLI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_FABulous_container
      - name: Run fabric generator flow and simulation with FABulous CLI
        run: |
          FABulous -c demo
          FABulous demo -fs ./demo/FABulous.tcl

  run_verilog_simulation_makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_FABulous_container
      - name: Run fabric generator flow and simulation with FABulous makefile
        run: |
          FABulous -c demo
          cd demo/Test
          make FAB_sim
