name: Test fabric generation against base branch

on: [push, pull_request]

jobs:
  run_sim_makefile_on_base_project:
    name: Run fabric generator flow and simulation with FABulous makefile against base branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Verilog
            type: verilog 
          - name: VHDL
            type: vhdl

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.base_ref }} 
      - uses: ./.github/actions/prepare_FABulous_container
      - name: generate old project
        run: |
          FABulous -c /tmp/demo_${{ matrix.type }} -w ${{ matrix.type }}

      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare_FABulous_container
      - name: Run fabric generator flow and simulation with FABulous makefile
        run: |
          cd /tmp/demo_${{ matrix.type }}/Test
          make FAB_sim
