name: Run pre-commit hooks

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Nix
        uses: ./.github/actions/setup-nix
      - name: Run pre-commit hooks
        run: |
          nix develop --command pre-commit run --all-files
