name: Testing with pytest and cocotb

on: [push, pull_request]


jobs:
  run_pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare_FABulous_container
        with:
          additional_system_packages: 'iverilog'
      - name: Run pytest
        run: pytest -v